/*
 * This file was generated by the Gradle 'init' task.
 */

import java.io.*
import java.util.*
val props = Properties()
FileInputStream(file("../gradle.properties")).use {
    props.load(it)
}

plugins {
    // Support convention plugins written in Kotlin. Convention plugins are build scripts in 'src/main' that automatically become available as plugins in the main build.
    `kotlin-dsl`
}

// Check settings.gradle for the real repositories list. Not sure why we need this one here.
repositories {
    // Use the plugin portal to apply community plugins in convention plugins.
    gradlePluginPortal()
    mavenCentral()
}

dependencies {
    // The kotlin version is defined in the 'gradle.properties' file.
    val kotlinVersion = props.getProperty("kotlinVersion")
    implementation("org.jetbrains.kotlin:kotlin-gradle-plugin:${kotlinVersion}")
    implementation("org.jetbrains.kotlin:kotlin-serialization")

    // Plugin for formatter
    implementation("com.diffplug.spotless:spotless-plugin-gradle:6.25.0")
}

